import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the complain slice
const initialState = {
    complainsList: [],
    loading: false,
    error: null,
    response: null,
};

// Create a slice for managing complain-related state
const complainSlice = createSlice({
    name: 'complain',
    initialState,
  reducers: {
    // Reducer to handle the start of a request
    getRequest: (state) => {
            state.loading = true;
    },
    // Reducer to handle a successful request
    getSuccess: (state, action) => {
            state.complainsList = action.payload;
            state.loading = false;
            state.error = null;
            state.response = null;
    },
    // Reducer to handle a request that failed with a message
    getFailed: (state, action) => {
            state.response = action.payload;
            state.loading = false;
            state.error = null;
    },
    // Reducer to handle a request that resulted in an error
    getError: (state, action) => {
            state.loading = false;
            state.error = action.payload;
        }
  },
});

// Export the action creators generated by createSlice
export const {
  getRequest,
  getSuccess,
  getFailed,
  getError,
} = complainSlice.actions;

// Export the reducer function generated by createSlice
export const complainReducer = complainSlice.reducer;
