import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the notice slice
const initialState = {
    noticesList: [],
    loading: false,
    error: null,
    response: null,
};
// Create a slice for managing notice-related state
const noticeSlice = createSlice({
    name: 'notice',
    initialState,
    reducers: {
        // Reducer to handle the start of a request
        getRequest: (state) => {
            state.loading = true;
        },
        // Reducer to handle a successful request
        getSuccess: (state, action) => {
            state.noticesList = action.payload;
            // Reset loading, error, and response states
            state.loading = false;
            state.error = null;
            state.response = null;
        },
        // Reducer to handle a request that failed with a message
        getFailed: (state, action) => {
            state.response = action.payload;
            // Reset loading and error states
            state.loading = false;
            state.error = null;
        },
        // Reducer to handle a request that resulted in an error
        getError: (state, action) => {
            // Set the error state with the payload error
            state.loading = false;
            state.error = action.payload;
        }
    },
});

export const {
    getRequest,
    getSuccess,
    getFailed,
    getError
} = noticeSlice.actions;
// Export the reducer function generated by createSlice
export const noticeReducer = noticeSlice.reducer;
